sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output 
