sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output  -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s
 sstacks -b 1 -p 24 -c ./cstacks_output/batch_1 -o ./sstacks_output -s 
