sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/100.24
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/101.24
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/102.24
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/103.25
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/10.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/104.25
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/105.25
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/106.25
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/107.25
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/108.26
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/109.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/110.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/111.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/112.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/113.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/11.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/114.27
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/115.28
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/116.28
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/117.28
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/118.28
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/119.29
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/1.1
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/120.29
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/121.30
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/122.31
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/123.32
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/12.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/124.33
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/125.34
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/126.34
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/127.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/128.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/129.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/130.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/131.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/132.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/133.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/13.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/134.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/135.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/136.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/137.35
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/138.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/139.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/140.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/141.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/142.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/143.36
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/14.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/144.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/145.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/146.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/147.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/148.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/149.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/150.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/151.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/152.37
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/153.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/15.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/154.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/155.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/156.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/157.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/158.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/159.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/160.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/161.38
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/162.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/163.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/16.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/164.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/165.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/166.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/167.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/168.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/169.39
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/170.40
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/171.41
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/172.41
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/173.41
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/17.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/174.41
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/175.42
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/176.43
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/177.44
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/178.44
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/179.45
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/180.45
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/181.46
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/182.46
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/183.46
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/18.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/184.46
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/185.47
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/186.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/187.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/188.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/189.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/190.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/191.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/192.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/193.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/19.3
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/194.48
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/195.49
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/196.49
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/197.50
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/198.51
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/199.51
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/200.51
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/201.52
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/202.53
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/203.54
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/204.55
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/20.4
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/205.55
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/206.56
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/207.56
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/208.56
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/209.56
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/210.57
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/211.57
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/212.58
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/213.58
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/214.58
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/21.4
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/215.58
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/216.59
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/217.59
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/218.60
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/219.60
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/2.1T
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/220.60
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/221.60
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/222.61
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/223.61
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/224.62
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/22.4
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/225.62
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/226.63
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/227.63
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/228.64
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/229.64
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/230.64
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/231.65
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/232.65
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/233.66
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/234.66
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/23.4
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/235.67
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/236.67
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/237.67
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/238.68
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/239.69
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/240.70
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/241.71
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/242.72
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/243.72
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/244.72
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/24.4
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/245.72
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/246.73
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/247.73
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/248.73
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/249.74
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/250.74
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/251.75
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/252.75
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/253.75
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/254.76
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/255.76
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/25.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/256.76
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/257.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/258.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/259.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/260.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/261.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/262.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/263.77
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/264.78
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/265.78
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/26.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/266.79
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/267.79
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/268.80
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/269.80
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/270.80
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/271.80
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/272.81
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/273.82
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/274.82
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/275.82
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/27.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/276.83
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/277.84
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/278.85
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/279.85
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/280.86
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/281.86
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/282.86
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/283.87
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/284.88
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/285.89
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/28.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/286.90
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/287.90
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/288.91
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/289.92
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/290.92
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/291.92
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/292.92
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/293.93
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/294.93
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/295.94
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/29.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/296.95
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/297.95
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/298.95
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/299.96
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/300.96
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/301.96
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/302.97
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/303.98
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/304.98
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/305.99
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/30.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/31.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/3.1
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/32.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/33.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/34.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/35.5
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/36.6
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/37.6
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/38.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/39.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/40.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/41.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/4.1
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/42.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/43.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/44.7
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/45.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/46.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/47.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/48.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/49.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/50.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/51.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/5.1
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/52.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/53.8
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/54.9
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/55.10
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/56.10
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/57.10
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/58.10
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/59.10
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/60.11
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/61.12
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/62.12
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/6.2
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/63.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/64.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/65.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/66.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/67.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/68.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/69.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/70.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/71.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/72.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/7.2
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/73.13
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/74.14
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/75.15
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/76.15
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/77.15
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/78.15
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/79.15
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/80.16
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/81.17
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/82.17
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/8.2
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/83.18
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/84.18
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/85.18
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/86.18
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/87.19
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/88.19
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/89.20
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/90.20
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/91.21
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/92.21
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/9.2
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/93.21
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/94.21
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/95.22
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/96.23
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/97.24
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/98.24
 sstacks -b 1 -p 24 -c ./cstacks_output -o ./sstacks_output  -s ./ustacks_output/99.24
