ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 1 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 2 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 3 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 4 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 5 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 6 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 7 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 8 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 9 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 10 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 11 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 12 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 13 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 14 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 15 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 16 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 17 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 18 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 19 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 20 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 21 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 22 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 23 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 24 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 25 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 26 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 27 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 28 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 29 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 30 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 31 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 32 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 33 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 34 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 35 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 36 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 37 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 38 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 39 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 40 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 41 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 42 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 43 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 44 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 45 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 46 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 47 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 48 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 49 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 50 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 51 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 52 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 53 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 54 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 55 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 56 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 57 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 58 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 59 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 60 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 61 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 62 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 63 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 64 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 65 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 66 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 67 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 68 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 69 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 70 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 71 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 72 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 73 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 74 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 75 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 76 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 77 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 78 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 79 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 80 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 81 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 82 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 83 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 84 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 85 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 86 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 87 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 88 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 89 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 90 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 91 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 92 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 93 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 94 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 95 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 96 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 97 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 98 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 99 -f 
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 100 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 101 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 102 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 103 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 104 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 105 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 106 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 107 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 108 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 109 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 110 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 111 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 112 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 113 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 114 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 115 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 116 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 117 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 118 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 119 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 120 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 121 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 122 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 123 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 124 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 125 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 126 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 127 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 128 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 129 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 130 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 131 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 132 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 133 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 134 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 135 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 136 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 137 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 138 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 139 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 140 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 141 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 142 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 143 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 144 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 145 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 146 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 147 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 148 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 149 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 150 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 151 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 152 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 153 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 154 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 155 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 156 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 157 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 158 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 159 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 160 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 161 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 162 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 163 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 164 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 165 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 166 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 167 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 168 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 169 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 170 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 171 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 172 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 173 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 174 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 175 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 176 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 177 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 178 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 179 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 180 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 181 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 182 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 183 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 184 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 185 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 186 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 187 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 188 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 189 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 190 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 191 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 192 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 193 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 194 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 195 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 196 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 197 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 198 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 199 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 200 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 201 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 202 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 203 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 204 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 205 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 206 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 207 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 208 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 209 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 210 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 211 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 212 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 213 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 214 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 215 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 216 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 217 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 218 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 219 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 220 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 221 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 222 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 223 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 224 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 225 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 226 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 227 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 228 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 229 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 230 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 231 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 232 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 233 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 234 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 235 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 236 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 237 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 238 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 239 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 240 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 241 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 242 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 243 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 244 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 245 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 246 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 247 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 248 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 249 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 250 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 251 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 252 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 253 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 254 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 255 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 256 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 257 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 258 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 259 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 260 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 261 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 262 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 263 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 264 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 265 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 266 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 267 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 268 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 269 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 270 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 271 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 272 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 273 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 274 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 275 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 276 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 277 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 278 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 279 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 280 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 281 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 282 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 283 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 284 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 285 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 286 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 287 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 288 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 289 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 290 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 291 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 292 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 293 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 294 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 295 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 296 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 297 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 298 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 299 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 300 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 301 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 302 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 303 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 304 -f
ustacks -t fastq -o ./ustacks_output  -m 3 -M 2 -i 305 -f
